services:
  scoring-api:
    image: redteamsubnet61/rest-scoring-api:3.0.0-251224
    build:
      context: .
    restart: unless-stopped
    privileged: true
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      RT_SCORING_API_PORT: ${RT_SCORING_API_PORT:-47920}
      RT_SCORING_API_HOTKEY_NAME: ${RT_SCORING_API_HOTKEY_NAME:-scoring-api}
    env_file:
      - path: .env
        required: false
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./volumes/storage/sidecar-btcli/data:/var/lib/sidecar-btcli"
    ports:
      - "${RT_SCORING_API_PORT:-47920}:${RT_SCORING_API_PORT:-47920}"
    tty: true
